version: '3.8'

services:
  application-share:
    image: ghcr.io/donskyblock/application-share:latest
    container_name: application-share
    restart: unless-stopped
    ports:
      - "3000:3000"    # Web interface
      - "5900:5900"    # VNC
      - "3389:3389"    # RDP
    environment:
      # Server Configuration
      - HOST=0.0.0.0
      - PORT=3000
      - DEBUG=false
      
      # Admin User
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-changeme123}
      
      # X11 Configuration
      - DISPLAY=:99
      - VNC_PORT=5900
      - VNC_PASSWORD=${VNC_PASSWORD:-vncpass123}
      - ENABLE_VNC=true
      
      # RDP Configuration
      - RDP_PORT=3389
      - RDP_PASSWORD=${RDP_PASSWORD:-rdppass123}
      - ENABLE_RDP=true
      
      # Streaming Configuration
      - STREAM_PORT=8080
      - STREAM_FRAME_RATE=30
      - STREAM_QUALITY=high
      
      # Security
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-jwt-key-change-this}
      - SESSION_SECRET=${SESSION_SECRET:-your-super-secret-session-key-change-this}
      
      # Application Limits
      - MAX_CONCURRENT_APPS=10
      - ALLOWED_APPLICATIONS=firefox,chrome,code,libreoffice,gedit,nautilus
      
      # Audio Configuration
      - ENABLE_AUDIO=true
      - AUDIO_SAMPLE_RATE=44100
      
      # File Transfer
      - MAX_FILE_SIZE=100MB
      - ALLOWED_FILE_TYPES=pdf,doc,docx,txt,jpg,png,gif,mp4,mp3
      
      # Session Management
      - MAX_SESSIONS=5
      - SESSION_TIMEOUT=3600
      
      # WebRTC Configuration
      - ENABLE_WEBRTC=true
      - WEBRTC_STUN_SERVERS=stun:stun.l.google.com:19302
      
      # Recording
      - ENABLE_RECORDING=true
      - RECORDING_PATH=/app/recordings
      
      # Advanced Features
      - ENABLE_MARKETPLACE=true
      - ENABLE_CUSTOM_LAUNCHERS=true
      - ENABLE_CLIPBOARD_SYNC=true
      
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
      - app_recordings:/app/recordings
      - app_uploads:/app/uploads
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      
    devices:
      - /dev/dri:/dev/dri  # GPU access for hardware acceleration
      
    cap_add:
      - SYS_ADMIN
      - DAC_OVERRIDE
      
    security_opt:
      - seccomp:unconfined
      
    networks:
      - app_network

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: application-share-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - application-share
    networks:
      - app_network
    profiles:
      - production

volumes:
  app_data:
    driver: local
  app_logs:
    driver: local
  app_recordings:
    driver: local
  app_uploads:
    driver: local

networks:
  app_network:
    driver: bridge
