apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: application-share-data
  namespace: application-share
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: application-share-logs
  namespace: application-share
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
